### ISSUE TITLE
Have you published all your Jokes?

### ISSUE THREAD

**Issue by RashmiRam** [cassidoo/ama#10]
I am just loving your Jokes & Memes. So, stalked you digitally left and right for an hour to find all the jokes made by you. 
I haven't come across any pages/newsletters exclusively for your Jokes. Have you published it already? If so, How can I get/buy that? If not, Would you please do so?

**Comment by cassidoo** [comment]
Hey! Hahaha thank you :)

I think the closest thing is my weekly newsletter, where I have a joke every week: cassidoo.co/newsletter

What else would you be interested in? I love the idea of publishing something more legit but I am not sure what people would want to read/consume!

**Comment by RashmiRam** [comment]
If you ask me, I would be interested in reading something which has only these tech satirical/witty jokes. Yours are just gold.
