### ISSUE TITLE
Developer experience vs developer advocacy vs developer relations

### ISSUE THREAD

**Issue by chopfitzroy** [cassidoo/ama#12]
Heya! 👋

I was hoping you might be able to help shed some light on the differences between developer experience, developer advocacy, and developer relations. I have been trying to figure out if they are essentially the same thing with different titles or if they each fit into their own niche. There is no real consensus online, some people seem to think they are the same thing while others are able to categorize them more accurately.

I ask because I am trying to define a new role and I _think_ it would be best classified as developer experience engineer or similar but I am wondering if the other two titles are a better fit. I thought you may have some insight to this given your current role 😅 .

The role is a mix of development, technical writing, liaising between other internal development teams as well as more conventional teams like marketing, sales, etc... It will also have a strong focus on code review and helping to develop best practice and facilitate it's adoption throughout the internal development teams. Most of the development in this role will be related to internal tools and systems including any custom tooling to aid in development efficiency.

Thanks heaps for taking the time to read this! 🙏

**Comment by cassidoo** [comment]
Hey!

Honestly... they are all the same thing. Whenever someone tries to define one differently from the other, someone else will swap the definitions.

The spectrum of the role is either being more on community management and marketing, or engineering and UX. A large amount of them is a combo of all of the above. 

At Netlify, [we published this post](https://www.netlify.com/blog/2021/01/06/developer-experience-at-netlify) to try and clarify it a bit more in how we define it!

**Comment by chopfitzroy** [comment]
Heya, thank you so much for this! And that article looks amazing I will be reading that on my lunch break! Really appreciate you taking the time to respond 🙏
