### ISSUE TITLE
How do you balance the physical aspect of coding?

### ISSUE THREAD

**Issue by Storms-Engineering** [cassidoo/ama#13]
How do you deal with the issue of sitting a desk for 8+ hours a day?  Do you use a standing desk, or do you have to get up and walk around a lot?  Also what about eye strain? (I guess breaks also help with that)   Just curious about your thoughts.

Thanks

**Comment by cassidoo** [comment]
Great question! I do have a desk that can be a standing desk (which I admit I should use more). I try to get up and walk around as much as I can, and I try to purposefully look away from my computer screen from time to time. I also have blue light glasses, and a few things like wrist splints, a [TheraBand](https://www.amazon.com/dp/B000KGOMBC?ref=exp_cassidoo_dp_vv_d) for stretching, a [hand massager](https://www.amazon.com/dp/B08RD15ZJJ/?ref=idea_lv_dp_ov_d&tag=onamzcassid07-20&linkCode=ic6&ascsubtag=amzn1.ideas.2SHBER3AZBLT2), and [a Black Roll Smart Move board](https://smooveboard.com) to help with other ergonomic things!

**Comment by Storms-Engineering** [comment]
Cool thanks for the response!
