### ISSUE TITLE
Potential content for an SO podcast?

### ISSUE THREAD

**Issue by intermezzio** [cassidoo/ama#15]
Hello! I'm a student at Olin College of Engineering, an unconventional (and tiny!) engineering school with a unique approach to teaching CS (including courses heavily focused on practical applications of software development as opposed to a theoretical approach). I believe some of our unique courses on software would make great content on the SO podcast. Would you be interested in learning more? I can give you more details or connect you with one of my professors. Thanks! (Also the concept of an ama repo is rather clever)

**Comment by cassidoo** [comment]
Hey @intermezzio! I've got a few friends who loved attending Olin! That sounds pretty cool. If you email podcast@stackoverflow.com, you can send in a pitch for an episode (mention that you brought it up to me first), and I think the team would love to get that scheduled! <3
