### ISSUE TITLE
Tech startup 

### ISSUE THREAD

**Issue by merhmood** [cassidoo/ama#17]
Hello Cassidoo, I am Mahmud Suberu, the co-founder and CEO of Omnihale, a Nigerian startup. Our company aims to revolutionize the healthcare system through innovative software. We would love the opportunity to pitch our idea to you, and I assure you won't regret giving us a chance.

**Comment by cassidoo** [comment]
Hey Mahmud! I looked at your website and it seems really cool. I admit I don't really invest in healthcare-oriented companies (because I don't have expertise in the space), but I appreciate you reaching out!

**Comment by merhmood** [comment]
Thanks, I appreciate the feedback. If there’s any way you can help, I will really love that
