### ISSUE TITLE
Terminal Setup

### ISSUE THREAD

**Issue by larson-carter** [cassidoo/ama#2]
What is your current terminal setup?

Do you use Oh My Zsh?

**Comment by cassidoo** [comment]
I use iTerm, and yes I use Oh My Zsh! I was kind of bummed getting my new work laptop that bash wasn't the default (because I had such an established bash profile that no longer worked), but so far I've been happy with Oh My Zsh and adding in my own aliases as I go.

**Comment by larson-carter** [comment]
That is so amazing to see that you use Oh My Zsh! If you want to come into our discord and show off your setup please do!

discord.gg/ohmyzsh we will be glad to have you!
