### ISSUE TITLE
How to pin a README.md on the overview page

### ISSUE THREAD

**Issue by JiaxiangBU** [cassidoo/ama#4]
I read your GitHub profile and like your arrangement. Maybe this question is related to the usage of GitHub.
How to pin the README.md as the personal intro on the profile page?

Here is a screenshot.
![image](https://user-images.githubusercontent.com/15884785/87139771-0e2dec00-c2d3-11ea-8ef2-d21494a3cc69.png)

**Comment by borjacampina** [comment]
Create a new public repository with your github username as repository name

**Comment by cassidoo** [comment]
Yup, just like @borjacampina said! So you, OP, would make a repo called `JiaxiangBU` :)

**Comment by JiaxiangBU** [comment]
Thanks @borjacampina @cassidoo I will try it
