### ISSUE TITLE
Important lessons from the last couple of years?

### ISSUE THREAD

**Issue by BlueHatbRit** [cassidoo/ama#5]
A pretty board question here so bare with 😄 It looks like your career has moved really quickly over the last few years (from an outside perspective), a few job changes, lots of streaming and growth on patereon etc. I'm wondering if there are any things you've learned outside of engineering over the last few years which you bring back to your engineering?

**Comment by cassidoo** [comment]
Hmm, I think the thing I've learned the most is that a job title, huge salary, and being "the boss" is not endgame for me. When I first got into the industry I thought it was, and I said "yes" to way too many things, and burned out way too many times trying to do everything. While it was great for getting to where I am today, I can't truly say whether or not it was all worth it. Being a member of a good, kind, productive team where I can learn and grow is more important to me than being in charge of something big. I am definitely privileged to be in this position to have this as an option for myself.
