### ISSUE TITLE
How did you get into Computer Science?

### ISSUE THREAD

**Issue by MarkoShiva** [cassidoo/ama#7]
the question is mostly about your path in Computer Science. Have you started as a CS student or you ware studying something else. 
What you wanted to be or do as a young girl? 
What kept you motivated to move into the CS and stay into the developer role?

**Comment by cassidoo** [comment]
These two questions should answer your questions!
- https://github.com/cassidoo/ama#do-you-have-a-cs-degree-do-you-regret-it
- https://github.com/cassidoo/ama#what-inspired-you-to-learn-how-to-code

Also, when I was young, I wanted to be an architect or "car designer" :)
