### ISSUE TITLE
Looking for some feedback/inputs on GraphQL at Edge

### ISSUE THREAD

**Issue by bishwenduk029** [cassidoo/ama#9]
Hello @cassidoo ,

Hope you are doing fine. 

As you have worked on multiple projects with NextJs. I was hoping to get your feedback on one of the [PR](https://github.com/flareact/flareact/pull/103) I have raised for [flareact](https://flareact.com/) a NextJS inspired framework operating on CloudFlare workers. The PR is currently in progress and if possible if you could please take some time to share any feedback/input on GraphQL execution and caching at Edge it would be great.

Thanks in advance.

**Comment by cassidoo** [comment]
Hope you're well too! I am not familiar with this project (seems neat though), so I don't think my feedback would be very valuable. Sorry about that.
